--- #YAML:1.0
name:                MojoX-Encode-Gzip
version:             1.10
abstract:            Gzip a Mojo::Message::Response
license:             ~
author:              
    - Mark Stosberg <mark@summersault.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Compress::Zlib:                0
    Mojo:                          0.999925
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
